const AUTH_SECRET = process.env.AUTH_SECRET;
const AUTH_GOOGLE_ID = process.env.AUTH_GOOGLE_ID;
const AUTH_GOOGLE_SECRET = process.env.AUTH_GOOGLE_SECRET;
const DATABASE_URL = process.env.DATABASE_URL;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

export {
    AUTH_SECRET,
    AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET,
    DATABASE_URL,
    GEMINI_API_KEY,
}